language: android
android:
        components:
                - platform-tools
                - tools
                - build-tools-20.0.0
                - android-20
                - extra-android-m2repository
                - extra-android-support

